ferranbt/fastssz

Makefile
spectests/external/bytes.go
spectests/structs.go
spectests/structs_encoding.go
sszgen/hash.go
sszgen/main.go
sszgen/marshal.go
sszgen/size.go
sszgen/unmarshal.go

This PR adds support for fields in the struct that are references in another package. It supports two forms:
- Fixed types for []byte and [x]byte
- Dynamic types that implement the Marshaler, Unmarshaler and HashRoot interface.

External references

---

sszgen/main.go

If `sszgen` is run in a directory that contains tests it fails to generate the required files.  This patch ignores any packages ending in `_test` when obtaining the files for which to generate the SSZ functions.

Ignore test packages when reading AST.

---

Makefile
spectests/external/bytes.go
spectests/external2/external.go
spectests/structs.go
spectests/structs_encoding.go
sszgen/main.go

There was not importing for basic types only complex (vector, containers, references). The previous PR worked because the uint alias was on the same package as other complex types.

Fix import alias of basic types

---

hasher.go
sszgen/hash.go

To stay consistent I added the `PutUint` methods to `Hasher`. But I also noticed `MarshalUint` methods are very similar. Do you think they can be re-used here?

Fix hashing non-64-bit uints

---

sszgen/main.go

This PR adds a check for imports that have a "_" alias to skip its decoding.

Skip imports for _ alias

---

hasher.go
proof.go
tests/codetrie.go
tests/codetrie_encoding.go
tests/codetrie_test.go
tree.go
tree_test.go

This PR adds initial support for multiproof generation. The implementation is inefficient, but we can iterate on that.
It was easier to generate a proof given a tree-backing of the SSZ structure. So the file `tree.go` has generic methods for creating a tree (and getting a leaf in a tree). Apart from these generic ones we need methods generated for each SSZ type to get its tree backing. I have examples of those in `tests/codetrie.go`.
Oh and we can later on merge the file `proof.go` into `tree.go`. I didn't do it in this PR because the diff is already large (sorry about that).

Generate multiproof

---

proof.go
tests/codetrie_test.go
tree_test.go

There was an inefficiency in the proof when two (or more) sibling leaves were part of the proof. In that case both the `Hashes` section and the `Leaves` section of the proof contained all siblings.

Remove duplicate leaves from proof

---

encode.go
spectests/structs_encoding.go
spectests/structs_test.go
sszgen/unmarshal.go

Fixes https://github.com/ferranbt/fastssz/issues/44 by adding a bounds check to UnmarshalSSZ, in the unmarshaling logic of the first offset in each message. For an example of the new output please see:
https://github.com/prysmaticlabs/ethereumapis/blob/check-variable-offset/eth/v1/generated.ssz.go#L81

Ensure variable offsets point beyond fixed values

---

sszgen/main.go

As title describes. This will help with our build tooling at github.com/prysmaticlabs/prysm

Exit with a non-zero status code when tool fails to encode

---

sszgen/main.go

Output before:
```
[ERR]: failed to encode SigningData: could not find struct with name 'Hash'exit status 1
```
After:
```
[ERR]: failed to encode SigningData: could not find struct with name 'Hash'
exit status 1
```

sszgen: output formatting in case of error

---

sszgen/generator/generator.go

This PR propagates the error when `encodeItem` fails.

Add error logs to encodeItem

---

hasher.go
wrapper.go

This PR adds an explicit assertion for the `HashWalker` interface for `Hasher` and `Wrapper`.

Assert HashWalker interface

---

CHANGELOG.md
sszgen/generator/generator.go
sszgen/main.go

At current the encoded file name is hardcoded to have the suffix 'encoding'.  This allows the suffix to be changed as a command line option.

Make suffix an option.

---

sszgen/generator/generator.go

Fixes #128, cause - shadowed variable `name`

Fix incorrect error message

---

.gitignore
README.md
go.mod
go.sum
hasher_test.go
spectests/structs_test.go

@ferranbt prysm implemented the byte slice hasher you were maintaining a fork for.

chore(deps): Unfork `gohashtree`

---

spectests/structs_encoding.go
sszgen/generator/marshal.go
sszgen/testcases/case1_encoding.go
sszgen/testcases/case7_encoding.go
sszgen/testcases/container_encoding.go
sszgen/testcases/issue_127_encoding.go
tests/codetrie_encoding.go

In the generated code, when processing the last variable field in a container, we don't need to update the offset as there is no next variable field that uses the offset.
The PR also removes redundant statements in `marshalContainer`.

chore(sszgen): Remove redundant generated code

---

tree.go
tree_test.go

Repeatedly running `Prove()` against the same node can take a long time, as hashes are unconditionally recomputed.  This simple change checks for the presence of a value in an intermediate node before rehashing.
Performance difference as follows:
```
goos: linux
goarch: amd64
pkg: github.com/ferranbt/fastssz
cpu: 12th Gen Intel(R) Core(TM) i7-1265U
│    before.txt    │              after.txt               │
│      sec/op      │    sec/op     vs base                │
Prove-12   247529.077µ ± 5%   4.283µ ± 34%  -100.00% (p=0.002 n=6)
```
This also returns the value being proved even if it is an intermediate node.
Test for repeated proving and a benchmark for repeated proving included.

Increase performance of repeat proving.

---

hasher.go

This PR fixed a leaky allocation that happens in `merkleizeImpl`.
Specifically, https://github.com/ferranbt/fastssz/blob/main/hasher.go#L379 expands the input slice:
```go
if oddNodeLength {
// is odd length
input = append(input, zeroHashes[i][:]...)
layerLen++
}
```
but the problem is that the input slice is a sub-slice of h.buf, so if the expansion needs to allocate a new buffer because we're at capacity, then the newly allocated memory area gets thrown away and will not be piled into h.buf to be used subsequently. The result is that calls in a loop will allocate in a loop.
You can verify this by hashing `DepositData` for example, where the last field is 96 bytes, requiring a 32 byte expansion, but since it's at the end of the buffer, it will trigger the case.

Fix spurious allocation in hasher.Merkleize

---

proof.go

This PR provides a more detailed description of how the `VerifyMultiproof` function should be used for verifying Merkle multi-proofs.
This allows an easier integration with other code which may not use this library to generate the proofs in the first place.

docs(multiproof): explain ordering of arguments

---

README.md

This pull request fixes the typo "reposity" to "repository" in the `README.md` file. The change ensures correct spelling in the documentation.
- Fixed the typo "reposity" to "repository" in the `README.md` file.
- `README.md`
- No testing is required since this change is limited to documentation and does not affect functionality.
- Ensuring correct spelling enhances the clarity and professionalism of the documentation.
---
Thank you for reviewing this change!

typo fix Update README.md

---

.github/workflows/pr.yaml

Bumps checkout to v4 for future-proofing against Node 20 runner updates. Workflows compile the same.

chore(ci): upgrade checkout to v4

---

.github/workflows/pr.yaml

PR updates the GitHub Action `actions/setup-go` from version v1 to the latest stable version v4 for improved performance, security, and compatibility.  
Reference: https://github.com/actions/setup-go

Update setup-go action to latest version

---

sszgen/generator/generator.go
sszgen/generator/hash.go
sszgen/generator/ir.go
sszgen/generator/marshal.go
sszgen/generator/size.go
sszgen/generator/tag_parser.go
sszgen/generator/unmarshal.go
sszgen/generator/validate.go

This PR introduces an internal Intermediate Representation (IR) system to replace the existing type handling approach in the fastssz code generator. The change refactors the type system from using simple enum-based types (TypeBytes, TypeUint, etc.) to a more structured interface-based design with specific type structs (*Bytes, *Uint, *Vector, etc.).

Add internal IR

---

encode.go
interface.go
spectests/structs_encoding.go
sszgen/generator/generator.go
sszgen/generator/ir.go
sszgen/generator/unmarshal.go
sszgen/main.go
sszgen/testcases/case1_encoding.go
sszgen/testcases/case4_encoding.go
sszgen/testcases/case5_encoding.go
sszgen/testcases/case7_encoding.go
sszgen/testcases/container_encoding.go
sszgen/testcases/integration_uint_encoding.go
sszgen/testcases/issue_127_encoding.go
sszgen/testcases/issue_156_encoding.go
sszgen/testcases/issue_166_encoding.go
sszgen/testcases/issue_188_encoding.go
sszgen/testcases/list_encoding.go
sszgen/testcases/pr_152_encoding.go
tests/codetrie_encoding.go

This PR removes the boilerplate that was required to unmarshal array types of dynamic size.

Remove unmarshal boilerplate for dynamic size fields
